import React from "react";
import jsPDF from 'jspdf';

const AdvisoryBox = ({ advisory }) => {
    if (!advisory || advisory.length === 0) return null;

    const downloadPdf = () => {
        const pdf = new jsPDF('p', 'mm', 'a4');
        let yPosition = 20;

        // Title
        pdf.setFontSize(20);
        pdf.setFont('helvetica', 'bold');
        pdf.text('FARMER WEATHER ADVISORY', 20, yPosition);
        yPosition += 15;

        // Subtitle
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'normal');
        pdf.text('Critical insights for your farming decisions', 20, yPosition);
        yPosition += 20;

        // Advisory items
        advisory.forEach((item, index) => {
            const isRisk = item.toLowerCase().includes("avoid") || item.toLowerCase().includes("monitor") || item.toLowerCase().includes("do not");
            const label = isRisk ? 'WARNING:' : 'ADVICE:';

            // Label
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'bold');
            pdf.setTextColor(isRisk ? 230 : 46, isRisk ? 81 : 125, isRisk ? 0 : 50); // Orange for risk, green for advice
            pdf.text(label, 20, yPosition);
            yPosition += 10;

            // Item text
            pdf.setFontSize(12);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(0, 0, 0); // Black

            // Split long text into lines
            const lines = pdf.splitTextToSize(item, 170);
            lines.forEach(line => {
                if (yPosition > 270) { 
                    pdf.addPage();
                    yPosition = 20;
                }
                pdf.text(line, 20, yPosition);
                yPosition += 7;
            });

            yPosition += 10; 
        });

        // Additional Recommendations Section
        if (yPosition > 250) { // Check if we need a new page
            pdf.addPage();
            yPosition = 20;
        } else {
            yPosition += 20; // Space before new section
        }

        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(46, 125, 50); // Green
        pdf.text('ADDITIONAL RECOMMENDATIONS', 20, yPosition);
        yPosition += 15;

        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(0, 0, 0);

        const recommendations = [
            "Monitor soil moisture levels regularly to prevent over or under watering.",
            "Consider crop rotation to maintain soil health and reduce pest risks.",
            "Keep records of weather patterns and their impact on your crops for future planning.",
            "Consult local agricultural extension services for region-specific advice.",
            "Ensure proper drainage to avoid waterlogging during heavy rains.",
            "Use weather forecasts to plan harvesting and planting activities.",
            "Protect crops from extreme temperatures with appropriate coverings or irrigation."
        ];

        recommendations.forEach(rec => {
            const lines = pdf.splitTextToSize(rec, 170);
            lines.forEach(line => {
                if (yPosition > 270) {
                    pdf.addPage();
                    yPosition = 20;
                }
                pdf.text(line, 20, yPosition);
                yPosition += 7;
            });
            yPosition += 5; // Small space between recommendations
        });

        // Footer
        if (yPosition > 250) {
            pdf.addPage();
            yPosition = 20;
        } else {
            yPosition += 20;
        }

        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(100, 100, 100);
        pdf.text('Generated by Farmer Weather Advisory Tool', 20, yPosition);
        yPosition += 10;
        pdf.text('For educational and informational purposes only. Always consult local experts for critical decisions.', 20, yPosition);

        pdf.save("FarmerAdvisory.pdf");
    };

    return (

        <div
            id="advisory-content"
            className="card-box advisory-box"
        >
            {/* Enhanced Header */}
            <div className="advisory-header">
                <div className="advisory-icon">📢</div>
                <div className="advisory-title">
                    <h3>FARMER WEATHER ADVISORY</h3>
                    <div className="advisory-subtitle">Critical insights for your farming decisions</div>
                </div>
            </div>

            {/* Advisory Content */}
            <div className="advisory-content">
                {advisory.map((a, i) => {

                    const isRisk = a.toLowerCase().includes("avoid") || a.toLowerCase().includes("monitor") || a.toLowerCase().includes("do not");
                    const className = isRisk ? "advisory-item risk" : "advisory-item advice";

                    return (

                        <div
                            key={i}
                            className={className}
                        >
                            <div className="advisory-item-icon">
                                {isRisk ? '🚨' : '✅'}
                            </div>
                            <div className="advisory-item-content">
                                <div className="advisory-item-label">
                                    {isRisk ? 'WARNING' : 'ADVICE'}
                                </div>
                                <div className="advisory-item-text">
                                    {a}
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>

            {/* Actions */}
            <div className="advisory-actions">
                <button
                    onClick={downloadPdf}
                    className="download-btn"
                >
                    <span className="btn-icon">📄</span>
                    Download Advisory (PDF)
                </button>
            </div>
        </div>
    );
};

export default AdvisoryBox;